export const GET_BLOCKED_CONTENT = 'GET_BLOCKED_CONTENT';
export const GET_BLOCKED_CONTENT_LOAD = 'GET_BLOCKED_CONTENT_LOAD';
export const GET_BLOCKED_CONTENT_SUCESS = 'GET_BLOCKED_CONTENT_SUCESS';
export const GET_BLOCKED_CONTENT_FAIL = 'GET_BLOCKED_CONTENT_FAIL';

export const BLOCKED_VIDEOS_STORAGE_KEY = 'blockedVideos'
export const BLOCKED_CHANNELS_STORAGE_KEY = 'blockedChannels'
export const BLOCKED_TITLES_STORAGE_KEY = 'blockedTitles'

export const BLOCK_VIDEO = 'BLOCK_VIDEO';
// export const UNBLOCK_VIDEO = 'UNBLOCK_VIDEO';
// export const BLOCK_CHANNEL = 'BLOCK_CHANNEL';
// export const UNBLOCK_CHANNEL = 'UNBLOCK_CHANNEL';
// export const BLOCK_TITLE = 'BLOCK_TITLE';
// export const UNBLOCK_TITLE = 'UNBLOCK_TITLE';